INSERT INTO T_COUNTRY(NAME,NAME_EN,WORD2,WORD3,CODE,CURRENCY,CREATE_USER,CREATE_TIME) VALUES('中国大陆','CHINA','CN','CHN',156,'CNY',1,NOW());
INSERT INTO T_COUNTRY(NAME,NAME_EN,WORD2,WORD3,CODE,CURRENCY,CREATE_USER,CREATE_TIME) VALUES('中国台湾','TAIWAN, PROVINCE OF CHINA','TW','TWN',158,'TWD',1,NOW());
INSERT INTO T_COUNTRY(NAME,NAME_EN,WORD2,WORD3,CODE,CURRENCY,CREATE_USER,CREATE_TIME) VALUES('日本','JAPAN','JP','JPN',392,'JPY',1,NOW());
INSERT INTO T_COUNTRY(NAME,NAME_EN,WORD2,WORD3,CODE,CURRENCY,CREATE_USER,CREATE_TIME) VALUES('韩国','KOREA, REPUBLIC OF','KR','KOR',410,'KRW',1,NOW());
INSERT INTO T_COUNTRY(NAME,NAME_EN,WORD2,WORD3,CODE,CURRENCY,CREATE_USER,CREATE_TIME) VALUES('澳大利亚','AUSTRALIA','AU','AUS',36,'AUD',1,NOW());
INSERT INTO T_COUNTRY(NAME,NAME_EN,WORD2,WORD3,CODE,CURRENCY,CREATE_USER,CREATE_TIME) VALUES('美国','UNITED STATES','US','USA',840,'USD',1,NOW());
INSERT INTO T_COUNTRY(NAME,NAME_EN,WORD2,WORD3,CODE,CURRENCY,CREATE_USER,CREATE_TIME) VALUES('德国','GERMANY','DE','DEU',276,'EUR',1,NOW());
INSERT INTO T_COUNTRY(NAME,NAME_EN,WORD2,WORD3,CODE,CURRENCY,CREATE_USER,CREATE_TIME) VALUES('法国','FRANCE','FR','FRA',250,'EUR',1,NOW());
INSERT INTO T_COUNTRY(NAME,NAME_EN,WORD2,WORD3,CODE,CURRENCY,CREATE_USER,CREATE_TIME) VALUES('英国','UNITED KINGDOM','GB','GBR',826,'GBP',1,NOW());
